# Generated by Django 4.0 on 2022-04-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_rate_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mate_id', models.IntegerField(verbose_name='メイトID')),
                ('user', models.CharField(max_length=255, verbose_name='ユーザー名')),
            ],
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span', models.FloatField(default='', max_length=255, verbose_name='期間')),
                ('number_of_matches', models.IntegerField(default=0, verbose_name='試合数')),
                ('last_rate', models.IntegerField(default=1500, verbose_name='最終レート')),
                ('max_rate', models.IntegerField(default=1500, verbose_name='最高レート')),
                ('min_rate', models.IntegerField(default=1500, verbose_name='最低レート')),
                ('ave_rate', models.IntegerField(default=1500, verbose_name='平均レート')),
                ('median_rate', models.IntegerField(default=1500, verbose_name='中央値')),
                ('mate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_rate_analysis.user', verbose_name='メイトID')),
            ],
        ),
        migrations.CreateModel(
            name='CharResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter', models.CharField(default='', max_length=255, verbose_name='対戦したキャラ')),
                ('number_of_matches', models.IntegerField(default=0, verbose_name='試合数')),
                ('rate_balance', models.IntegerField(default=0, verbose_name='レート収支')),
                ('results', models.CharField(default='', max_length=100, verbose_name='戦績')),
                ('user_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_rate_analysis.userresult', verbose_name='ユーザーデータ')),
            ],
        ),
    ]
