# Generated by Django 4.0 on 2022-04-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_rate_analysis', '0002_user_userresult_charresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresult',
            old_name='mate_id',
            new_name='mate',
        ),
    ]
